### ISSUE TITLE
Only text working.

### ISSUE THREAD

**Issue by opsopus** [keshavvishwkarma/ScalableLayoutKit#2]
Nice SDK! Great idea, good job.
And I'll try add UIView to screen but doesn't work, just only text working.

Thanks and best

**Comment by keshavvishwkarma** [comment]
Glad to hear you liked my idea that again pull me into enhance it.

Right now it is working fine in all cases. It has only one requirement that you have to apply ‘auto-layout’ in the view.

Thank you for pulling my attention into it 👏👏👏
